# Generated by Django 5.0.6 on 2024-05-13 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='salontable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salon_name', models.CharField(max_length=50)),
                ('username', models.CharField(max_length=50)),
                ('owner_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=50)),
                ('phone_number', models.IntegerField()),
                ('city', models.CharField(max_length=50)),
                ('zip_code', models.IntegerField()),
                ('license', models.FileField(upload_to='')),
                ('password', models.CharField(max_length=50)),
                ('confirm_password', models.CharField(max_length=50)),
                ('action', models.CharField(default='pending', max_length=50)),
            ],
        ),
    ]
