# Generated by Django 5.0.6 on 2024-05-21 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_logintable'),
    ]

    operations = [
        migrations.CreateModel(
            name='servicetable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('salon_name', models.CharField(max_length=50)),
                ('service_name', models.CharField(max_length=40)),
                ('description', models.CharField(max_length=80)),
                ('amount', models.IntegerField()),
            ],
        ),
    ]
