# Generated by Django 5.0.6 on 2024-05-23 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_servicetable'),
    ]

    operations = [
        migrations.CreateModel(
            name='bookingtable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=50)),
                ('gender', models.CharField(max_length=10)),
                ('mobile', models.IntegerField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('appointment_date', models.DateField()),
                ('appointment_time', models.TimeField(default=True)),
                ('service_name', models.CharField(max_length=50)),
                ('stylist', models.CharField(max_length=50)),
                ('special_requests', models.TextField(blank=True, null=True)),
                ('status', models.CharField(max_length=50)),
                ('salon_name', models.CharField(max_length=50)),
                ('username', models.CharField(max_length=50)),
            ],
        ),
    ]
