# Generated by Django 5.0.6 on 2024-05-27 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0006_alter_bookingtable_mobile'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicetable',
            name='gender',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
