# Generated by Django 5.0.6 on 2024-05-27 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0008_servicetable_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='salontable',
            name='photo',
            field=models.FileField(default=1, upload_to=''),
            preserve_default=False,
        ),
    ]
