# Generated by Django 5.0.6 on 2024-05-27 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0009_salontable_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='salontable',
            name='time',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
