# Generated by Django 5.0.6 on 2024-05-28 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0010_salontable_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicetable',
            name='service_photo',
            field=models.FileField(default=1, upload_to=''),
            preserve_default=False,
        ),
    ]
