# Generated by Django 5.0.6 on 2024-05-29 06:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0011_servicetable_service_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookingtable',
            name='stylist',
        ),
    ]
