# Generated by Django 5.0.6 on 2024-05-29 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0013_remove_bookingtable_special_requests'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingtable',
            name='amount',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
