# Generated by Django 5.0.6 on 2024-05-29 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0015_remove_bookingtable_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookingtable',
            name='gender',
        ),
    ]
