# Generated by Django 5.0.6 on 2024-05-31 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0019_complaint'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usertable',
            name='gender',
        ),
    ]
