# Generated by Django 5.0.6 on 2024-06-04 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0022_contact'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='contact_no',
        ),
    ]
